// Hashes of prebuilt portable_pty_rs binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'portable_pty-v0.0.6+antgrid.2';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'pty-linux-x64.tar.gz',
    hash: '814a1e2859945c2c667b247873edb14cc16c82a27d042bf4abf60e1ce456fdc2',
  ),
  'linux-arm64': AssetHash(
    tarball: 'pty-linux-arm64.tar.gz',
    hash: '4e32d1f831368a1f3616ad273a15ea386ad584e93147f8dfd3476f7052706e87',
  ),
  'macos-arm64': AssetHash(
    tarball: 'pty-macos-arm64.tar.gz',
    hash: '2b7e2adbbb7a8bf4e5e145c0627d9913f71792b6566e451ff41e67d215127c0c',
  ),
  'macos-x64': AssetHash(
    tarball: 'pty-macos-x64.tar.gz',
    hash: '13bb51fa872d9afac0c4599b888111bb6540b26b6fe22dff619e1c7925597204',
  ),
  'windows-x64': AssetHash(
    tarball: 'pty-windows-x64.tar.gz',
    hash: 'be4de0e76bdd9609bb7854b94fd0529c4c602498afe6a7ac2737c57c871cfd59',
  ),
  'windows-arm64': AssetHash(
    tarball: 'pty-windows-arm64.tar.gz',
    hash: '9ca7461d5074c54a7ab0a950b32d408c034f6fb70771a12aa6ab977a154c9d58',
  ),
  'android-arm64': AssetHash(
    tarball: 'pty-android-arm64.tar.gz',
    hash: '51cc345ce8060223c0bf178611061ff5716d14d9f0a6c0c1ccf7a98021ea8d92',
  ),
  'android-arm': AssetHash(
    tarball: 'pty-android-arm.tar.gz',
    hash: '3aef38b36476a8ce4b5344594ea7de536409fa9337dcc3a4658175b076c44fd7',
  ),
  'android-x64': AssetHash(
    tarball: 'pty-android-x64.tar.gz',
    hash: 'd99feec672718ead325dc6da7fce5ca3df8cacc0c1e3fd608b19b9be925c4a5b',
  ),
  'ios-arm64': AssetHash(
    tarball: 'pty-ios-arm64.tar.gz',
    hash: '20f2c79ffcca3579dd8c406e5bf399a49aa9b1cb355ef217b66053dc6a681992',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'pty-ios-sim-arm64.tar.gz',
    hash: '2e5df92546c4698d2b85fded9fc32422aab436fa8578dc5b8c2737d3920c7db3',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'pty-ios-sim-x64.tar.gz',
    hash: 'c85c0d56ba95bb29bc01517743e1d5aab54a473f2a497fbee58db343041389c3',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "pty-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
