// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'ghostty_vte-v0.1.4';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: '6c676367a0e79beb767e85336941599e3fc290a4321ce82fcc4bd8b2fdc4a374',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: '2f10277bde3dfbfe9facacf133c1b5dd9beb11a938a19cf3226b16a9c42e74ea',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: '895bfb1fe7e74c98d7206d2232cddda43cea273755fd758fc83e0136333a3e67',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '06fe706046996b8ece761935e369ae5745ae00605ac9413b7b9050eeff756523',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: '2050567a04887066231f0118a8ff5583a3b733a86092ff8579fc6100227179d7',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: '02e5fc6ed942a19f20ded2f021c6629653db66b2487d39c5b91d7c5d08300396',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: '8e6a036d30a5712d05843f7cd78fe76b7f9da3f58ff49044bb870b63b4ee350d',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: '6203a573f37a95e7fb91a345a9e111e6fb3f37ac142ee577aad1aad20f1d1b16',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: '8f8c51efc1f03e843fdab2bd9a23d483aee577e0d429b0b9cbc0c7dd57ba2557',
  ),
  'ios-arm64': AssetHash(
    tarball: 'vte-ios-arm64.tar.gz',
    hash: 'c8d9f307b2f69470163b6dd85ca115c721ef3a215e7a9ee96dc625d5ff3f0dc6',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'vte-ios-sim-arm64.tar.gz',
    hash: 'a99d136b1d20c744313226d337c9ddf1faa0800c96e12c610f860e5669946f30',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'vte-ios-sim-x64.tar.gz',
    hash: '074f79d7104797618e02f7b4304bcf46f19f1aa687e530948f87f5ecaf83fd89',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
