// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'ghostty_vte-v0.1.4';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: '24b41debe04eb4c9cc62a294bc54edb4a678f5608583c551dbc543d4f489e792',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: 'cd24625c616353f6e2f62dd540eda20641d3a4b556c0c0ba8ebaa32eadb6ee9d',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: '807c4449f05b2f9e9d2a36cb9d3a7d7bad5fd0b0ec4471ba8e443792126c2be3',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '85769e6085dbcf97cd5e3dcef456d00ce5ddec9b64d8e40f709f054cb8d13d45',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: 'a4474703c0ce71b103e153bf7db7f4f3b13a804ddf5d45597590f9b10aed109b',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: '8d67a47dd9b1cbabbbe601e3dcebe5fcbbbe0971859e76bf83aa1f3f005ceb43',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: '344e5980d03c7114c9ff623fd4a63dcf7a96119a3469a60ee617dad9adce327f',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: '191b8ce1ca0ca9640a4b4a0d79144c4047f396169cc157cd1b8733a468010379',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: '9abe4b27a280c0fc0e327c752bfb92a87fe40cbe6af69340eb7559f07b3028bb',
  ),
  'ios-arm64': AssetHash(
    tarball: 'vte-ios-arm64.tar.gz',
    hash: '71d259c95a320e914657dddd1f95ff2ad25057c8dc9f92f577073d495777ad3a',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'vte-ios-sim-arm64.tar.gz',
    hash: '1b42591923477d55424b06e602291566b312abb9042e02d741dd986b3d93e9bd',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'vte-ios-sim-x64.tar.gz',
    hash: '26b1c62f42f87aebadf896e84ea8667d2235c2ed450574ca0ec76e1adea92bf0',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
